### ISSUE TITLE
Issue Adding the app to Teams

### ISSUE THREAD

**Issue by jerryyasir** [rabwill/tab-spfx-me-experience#2]
Hello Rabia,
Happy Weekend, almost Monday :)

I am working on a demo for this solution for my custom but facing issue while adding to my MVP Tenant.  Check the error below

Sorry, something went wrong
Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.
TECHNICAL DETAILS
Error details: Error: Error initializing application. Error: TypeError: Cannot read property 'id' of undefined
Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: dd53909f-4029-b000-3c11-37711e1f6c43
Date and Time: 11/22/2020 7:06:18 PM

Steps I did.
1. Package the Solutions.
2. Uploaded to SharePoint App Catalog
3. Click Allow in Teams - Admin Center - Manage Apps
4. Add Me Settings as App to Global App Settings.
5. Approve all Permissions in SharePoint Admin Center
6. Refresh Teams.

![MeSettingsError](https://user-images.githubusercontent.com/15963347/99926447-c5ba1c80-2d0f-11eb-8411-8e6015b48c27.png)

Am I missing something? 

Thanks in Advance.

**Comment by rabwill** [comment]
Hey @jerryyasir , thanks for informing about an issue, Are you able to get this webpart to work in a SharePoint page?

**Comment by jerryyasir** [comment]
> Hey @jerryyasir , thanks for informing about an issue, Are you able to get this webpart to work in a SharePoint page?

When I followed the basic steps you provided. I could not find both Planning and Insights Web parts on my SharePoint Site.  It was because I did not checked the "Make this web part available on all sites" option.  But later I realized that the web part intended use is Tab so option will be required.

I went back and deployed the package again by selecting the global deployment check box.  Insights web part worked but Planning failed, I repeated the same steps again to make sure, but this time the issue was reversed.  The Planning worked and Insights failed with the following error.  

Note

- I added both web parts on the same page.
- Insights Web part works fine on the separate page.

[SPLoaderError.loadComponentError]:
Failed to load component "eb958e51-9a32-46d6-aa5f-5c40336ff99d" (InsightsWebPart). Original error: Failed to load entry point from component "eb958e51-9a32-46d6-aa5f-5c40336ff99d" (InsightsWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry

INNERERROR:
Failed to load entry point from component "eb958e51-9a32-46d6-aa5f-5c40336ff99d" (InsightsWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry
CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_8b11239c06a5ff9d7483a17d343775d3.js:1:852821)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_8b11239c06a5ff9d7483a17d343775d3.js:1:998076)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_8b11239c06a5ff9d7483a17d343775d3.js:1:1038972)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_8b11239c06a5ff9d7483a17d343775d3.js:1:1035017)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_8b11239c06a5ff9d7483a17d343775d3.js:1:1027284

![Error](https://user-images.githubusercontent.com/15963347/99931541-ea6bbf80-2d22-11eb-801d-e06a74f1e30f.png)


Teams
I am not able to see Insights and Planning Tabs in Microsoft Teams (Add a Tab Page).  Only Me Experience App is there and it showed up after I enabled it on Teams Admin Center.

The Me Experience Error is gone but not sure what else I can do to add the tabs to any Team.
![Error1](https://user-images.githubusercontent.com/15963347/99931691-7c73c800-2d23-11eb-9fdf-9f988af50f48.png)

**Comment by jerryyasir** [comment]
Sorry for Spamming you but it was my bad as I did forgot a step to upload the Me.zip file.  Both Tabs are now working.

Actual Issue: Both web parts does not work on the same page

Thanks in advance.

**Comment by rabwill** [comment]
Thanks @jerryyasir  for confirming :) yes I think it is a bug with one or more SPFx webparts using MGT to co-exist in a SharePoint page , you can track it [here](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/229), not affected by it in our Teams app though.

**Comment by rabwill** [comment]
Since this is an issue with the product, closing it in my repository, please track issue [here](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/229)
