### ISSUE TITLE
Settings-Tab isn't able to load

### ISSUE THREAD

**Issue by kmbdsz** [rabwill/tab-spfx-me-experience#3]
Dear Rabia,

in some cases (with some users) the settings tab is not loading. There is just the loading icon on the page. 
Do you have any adive? 
To me it looks like some users just don't have the permission to run "_createSchemaExtension". 
(All API permissions within the sp admin center granted). Is there maybe another option which I have to enable?

Please help me out. 
Kind Regards,
Sebastian

**Comment by kmbdsz** [comment]
Already found the solution - webApplicationInfo was missing within the manifest (teams). Thanks

**Comment by rabwill** [comment]
Well done @kmbdsz and sorry for the delay in getting back to you!

**Comment by kmbdsz** [comment]
@rabwill I am really sorry to bother you again. Everything worked well and as expected - but in the last (don't know exactly) days the following error appears:

**settings-web-part_e3fe35dcc96bbb6ef2e29ff56723dd22.js:3311 Uncaught (in promise) TypeError: Cannot read property '_getSchemaExtension' of undefined

settings-web-part_e3fe35dcc96bbb6ef2e29ff56723dd22.js:3311 Uncaught (in promise) Error: Token retrieval timeout**

This error appears on two different tenants. Any ideas? Please help me out here.

Btw. within the workbench (<tenant>.sharepoint.com/_layouts/15/Workbench.aspx) and on a regualar sp-site (in my case - communcation site) its working as expected without errors.
